### ISSUE TITLE
the crc check of function of "mb_rtu_frm_make" is error!

### ISSUE THREAD

**Issue by TsingsongYoung** [qiyongzhong0/qmodbus#1]
int mb_rtu_frm_make(u8 *buf, const mb_rtu_frm_t *frm, mb_pdu_type_t type)//生成rtu帧, 返回帧长度
{
    u8 *p = buf;
    p += mb_cvt_u8_put(p, frm->saddr);
    p += mb_pdu_make(p, &(frm->pdu), type);
    u16 crc = mb_crc_cal(buf, (int)(p - buf));
 @   p += mb_cvt_u16_put(p, crc);     //mobus rtu crc is crc_L，then crc_H
    return((int)(p - buf));
}

**Comment by qiyongzhong0** [comment]
你最好验证一下是不是错的，qmodbus是经过使用验证过的，不存在CRC错误问题。

**Comment by largesun** [comment]
作者有验证过CRC吗，crc搞反了

**Comment by qiyongzhong0** [comment]
确实CRC高低字节反了，已完成修复。我原来用MThings做的测试，没发现CRC错误，竟然MThings没检验CRC。
