### ISSUE TITLE
RTU串口数据校验位和数据位不对

### ISSUE THREAD

**Issue by largesun** [qiyongzhong0/qmodbus#2]
当串口设置数据校验位时，数据位应为9

**Comment by largesun** [comment]
找设备系统测试下，提高软件包质量

**Comment by qiyongzhong0** [comment]
> 当串口设置数据校验位时，数据位应为9

有的MCU有校验位时数据位为9，有些则不是，所以不能统一为9处理。对于驱动不能统一兼容的MCU，使用时可以在应用模块中重新定义实现mb_port_rtu_open函数，modbus_port_xxx中的函数都是弱函数，在需要移植适配时可以重新定义实现。

**Comment by largesun** [comment]
建议去实际验证，对待bug不要只流于推理
